/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => YTranscriptPlugin
});
module.exports = __toCommonJS(main_exports);

// buffer-polyfill.js
if (typeof Buffer === "undefined") {
  globalThis.Buffer = {
    from: function(data) {
      if (data instanceof Uint8Array) {
        let binary = "";
        for (let i = 0; i < data.length; i++) {
          binary += String.fromCharCode(data[i]);
        }
        return {
          toString: function(encoding) {
            if (encoding === "base64") {
              return btoa(binary);
            }
            return binary;
          }
        };
      }
      return {
        toString: function(encoding) {
          if (encoding === "base64") {
            return btoa(String(data));
          }
          return String(data);
        }
      };
    }
  };
}

// src/main.ts
var import_obsidian6 = require("obsidian");

// src/transcript-view.ts
var import_obsidian3 = require("obsidian");

// src/youtube-transcript.ts
var import_obsidian = require("obsidian");

// src/types.ts
var YoutubeTranscriptError = class extends Error {
  constructor(err) {
    if (!(err instanceof Error)) {
      super("");
      return;
    }
    if (err.message.includes("ERR_INVALID_URL")) {
      super("Invalid YouTube URL");
    } else {
      super(err.message);
    }
  }
};

// src/api-parser.ts
var YOUTUBE_TITLE_REGEX = new RegExp(
  /<meta\s+name="title"\s+content="([^"]*)\">/
);
var YOUTUBE_VIDEOID_REGEX = new RegExp(
  /<link\s+rel="canonical"\s+href="([^"]*)\">/
);
function decodeHtmlEntities(text) {
  return text.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&apos;/g, "'").replace(
    /&#(\d+);/g,
    (_, code) => String.fromCharCode(parseInt(code, 10))
  ).replace(
    /&#x([a-fA-F0-9]+);/g,
    (_, code) => String.fromCharCode(parseInt(code, 16))
  ).replace(/\n/g, " ").trim();
}
function parseTranscriptXml(xmlContent) {
  const lines = [];
  const textMatches = xmlContent.matchAll(
    /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g
  );
  for (const match of textMatches) {
    const startSeconds = parseFloat(match[1]);
    const durationSeconds = parseFloat(match[2]);
    const text = decodeHtmlEntities(match[3].replace(/<[^>]+>/g, ""));
    if (text) {
      lines.push({
        text,
        offset: Math.round(startSeconds * 1e3),
        duration: Math.round(durationSeconds * 1e3)
      });
    }
  }
  if (lines.length === 0) {
    const pMatches = xmlContent.matchAll(
      /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g
    );
    for (const match of pMatches) {
      const offset = parseInt(match[1], 10);
      const duration = parseInt(match[2], 10);
      const text = decodeHtmlEntities(match[3].replace(/<[^>]+>/g, ""));
      if (text) {
        lines.push({
          text,
          offset,
          duration
        });
      }
    }
  }
  return lines;
}

// src/youtube-transcript.ts
var _YoutubeTranscript = class _YoutubeTranscript {
  static async getTranscript(url, config) {
    var _a, _b, _c, _d, _e, _f;
    try {
      const videoId = this.extractVideoIdFromUrl(url);
      if (!videoId) {
        throw new YoutubeTranscriptError(
          new Error(
            "Invalid YouTube URL - could not extract video ID"
          )
        );
      }
      console.log(`\u{1F3AC} Fetching transcript for video: ${videoId}`);
      const playerData = await this.fetchPlayerData(videoId, config);
      const title = ((_a = playerData.videoDetails) == null ? void 0 : _a.title) || "Unknown";
      const captionsData = (_b = playerData.captions) == null ? void 0 : _b.playerCaptionsTracklistRenderer;
      if (!captionsData || !captionsData.captionTracks) {
        throw new YoutubeTranscriptError(
          new Error("No captions available for this video")
        );
      }
      console.log(
        `\u{1F4DD} Found ${captionsData.captionTracks.length} caption track(s)`
      );
      const langCode = (config == null ? void 0 : config.lang) || "en";
      const captionTrack = this.findCaptionTrack(
        captionsData.captionTracks,
        langCode
      );
      if (!captionTrack) {
        const availableLangs = captionsData.captionTracks.map((t) => t.languageCode).join(", ");
        throw new YoutubeTranscriptError(
          new Error(
            `No transcript found for language '${langCode}'. Available: ${availableLangs}`
          )
        );
      }
      const trackName = ((_e = (_d = (_c = captionTrack.name) == null ? void 0 : _c.runs) == null ? void 0 : _d[0]) == null ? void 0 : _e.text) || ((_f = captionTrack.name) == null ? void 0 : _f.simpleText) || captionTrack.languageCode;
      console.log(
        `\u{1F504} Using caption track: ${trackName} (${captionTrack.languageCode})`
      );
      const transcriptUrl = captionTrack.baseUrl;
      console.log(
        `\u{1F4E5} Fetching transcript from: ${transcriptUrl.substring(0, 80)}...`
      );
      const lines = await this.fetchTranscriptFromUrl(transcriptUrl);
      console.log(
        `\u2705 Successfully fetched ${lines.length} transcript lines`
      );
      return {
        title: this.decodeHTML(title),
        lines
      };
    } catch (err) {
      if (err instanceof YoutubeTranscriptError) {
        throw err;
      }
      throw new YoutubeTranscriptError(err);
    }
  }
  /**
   * Extract video ID from various YouTube URL formats
   */
  static extractVideoIdFromUrl(url) {
    const patterns = [
      /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/v\/)([a-zA-Z0-9_-]{11})/,
      /^([a-zA-Z0-9_-]{11})$/
      // Just the video ID
    ];
    for (const pattern of patterns) {
      const match = url.match(pattern);
      if (match) {
        return match[1];
      }
    }
    return null;
  }
  /**
   * Fetches player data from YouTube's InnerTube API using ANDROID client
   */
  static async fetchPlayerData(videoId, config) {
    const context = {
      ..._YoutubeTranscript.INNERTUBE_CONTEXT,
      client: {
        ..._YoutubeTranscript.INNERTUBE_CONTEXT.client,
        hl: (config == null ? void 0 : config.lang) || "en",
        gl: (config == null ? void 0 : config.country) || "US"
      }
    };
    const requestBody = {
      context,
      videoId
    };
    console.log(`\u{1F504} Calling InnerTube Player API with IOS client...`);
    const response = await (0, import_obsidian.requestUrl)({
      url: _YoutubeTranscript.INNERTUBE_PLAYER_URL,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent": "com.google.ios.youtube/20.10.38 (iPhone16,2; U; CPU iOS 17_5_1 like Mac OS X)"
      },
      body: JSON.stringify(requestBody)
    });
    const data = JSON.parse(response.text);
    const playabilityStatus = data.playabilityStatus;
    if (playabilityStatus) {
      console.log(`\u{1F4CA} Playability status: ${playabilityStatus.status}`);
      if (playabilityStatus.status === "ERROR") {
        throw new Error(
          playabilityStatus.reason || "Video unavailable"
        );
      }
      if (playabilityStatus.status === "LOGIN_REQUIRED") {
        throw new Error("This video requires login to view");
      }
      if (playabilityStatus.status === "UNPLAYABLE") {
        throw new Error(
          playabilityStatus.reason || "Video is unplayable"
        );
      }
    }
    return data;
  }
  /**
   * Finds the best matching caption track for the requested language
   */
  static findCaptionTrack(captionTracks, langCode) {
    let track = captionTracks.find((t) => t.languageCode === langCode);
    if (track) return track;
    track = captionTracks.find(
      (t) => t.languageCode.startsWith(langCode + "-")
    );
    if (track) return track;
    track = captionTracks.find(
      (t) => langCode.startsWith(t.languageCode + "-")
    );
    if (track) return track;
    if (captionTracks.length > 0) {
      console.log(
        `\u26A0\uFE0F Language '${langCode}' not found, falling back to '${captionTracks[0].languageCode}'`
      );
      return captionTracks[0];
    }
    return null;
  }
  /**
   * Fetches transcript XML from the caption track URL
   */
  static async fetchTranscriptFromUrl(transcriptUrl) {
    const response = await (0, import_obsidian.requestUrl)({
      url: transcriptUrl,
      method: "GET",
      headers: {
        "Accept-Language": "en-US,en;q=0.9"
      }
    });
    console.log(
      `\u{1F4C4} Transcript response length: ${response.text.length} bytes`
    );
    if (response.text.length === 0) {
      throw new Error("Received empty transcript response");
    }
    return parseTranscriptXml(response.text);
  }
  /**
   * Decodes HTML entities in a text string
   */
  static decodeHTML(text) {
    return text.replace(/&#39;/g, "'").replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(
      /&#(\d+);/g,
      (_, code) => String.fromCharCode(parseInt(code, 10))
    ).replace(/\\n/g, " ").replace(/\s+/g, " ").trim();
  }
};
// YouTube's public InnerTube API key
_YoutubeTranscript.INNERTUBE_API_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";
_YoutubeTranscript.INNERTUBE_PLAYER_URL = `https://www.youtube.com/youtubei/v1/player?key=${_YoutubeTranscript.INNERTUBE_API_KEY}`;
// Use IOS client - ANDROID client no longer returns captions (early 2026).
// IOS client returns caption track URLs that work without PO tokens.
_YoutubeTranscript.INNERTUBE_CONTEXT = {
  client: {
    clientName: "IOS",
    clientVersion: "20.10.38",
    hl: "en",
    gl: "US"
  }
};
var YoutubeTranscript = _YoutubeTranscript;

// src/timestampt-utils.ts
var formatTimestamp = (t) => {
  if (t < 0) return "00:00";
  const fnum = (n) => `${n | 0}`.padStart(2, "0");
  const s = 1e3;
  const m = 60 * s;
  const h = 60 * m;
  const hours = Math.floor(t / h);
  const minutes = Math.floor((t - hours * h) / m);
  const seconds = Math.floor((t - hours * h - minutes * m) / s);
  const time = hours ? [hours, minutes, seconds] : [minutes, seconds];
  return time.map(fnum).join(":");
};

// src/render-utils.ts
var highlightText = (div, searchValue) => {
  const content = div.innerHTML;
  const highlightedContent = content.replace(
    new RegExp(searchValue, "gi"),
    '<span class="yt-transcript__highlight">$&</span>'
  );
  div.innerHTML = highlightedContent;
};
var getTranscriptBlocks = (data, timestampMod) => {
  const transcriptBlocks = [];
  let quote = "";
  let quoteTimeOffset = 0;
  data.forEach((line, i) => {
    if (i === 0) {
      quoteTimeOffset = line.offset;
      quote += line.text + " ";
      return;
    }
    if (i % timestampMod == 0) {
      transcriptBlocks.push({
        quote,
        quoteTimeOffset
      });
      quote = "";
      quoteTimeOffset = line.offset;
    }
    quote += line.text + " ";
  });
  if (quote !== "") {
    transcriptBlocks.push({
      quote,
      quoteTimeOffset
    });
  }
  return transcriptBlocks;
};

// src/services/SummarizationService.ts
var import_obsidian2 = require("obsidian");

// src/transcript-chunker.ts
var DEFAULT_MIN_SPLIT_RATIO = 0.6;
function normalizeChunk(chunk) {
  return chunk.trim();
}
function findBestSplitIndex(text, maxChars) {
  if (text.length <= maxChars) {
    return text.length;
  }
  const minSplit = Math.max(1, Math.floor(maxChars * DEFAULT_MIN_SPLIT_RATIO));
  const candidateWindow = text.slice(minSplit, maxChars + 1);
  const paragraphBreakIndex = candidateWindow.lastIndexOf("\n\n");
  if (paragraphBreakIndex !== -1) {
    return minSplit + paragraphBreakIndex + 2;
  }
  let sentenceBreakIndex = -1;
  for (let i = candidateWindow.length - 1; i >= 0; i -= 1) {
    const char = candidateWindow[i];
    const nextChar = candidateWindow[i + 1] || "";
    if ((char === "." || char === "!" || char === "?") && (!nextChar || /\s/.test(nextChar))) {
      sentenceBreakIndex = i;
      break;
    }
  }
  if (sentenceBreakIndex !== -1) {
    return minSplit + sentenceBreakIndex + 1;
  }
  const lineBreakIndex = candidateWindow.lastIndexOf("\n");
  if (lineBreakIndex !== -1) {
    return minSplit + lineBreakIndex + 1;
  }
  return maxChars;
}
function splitIntoChunks(text, maxChars) {
  if (!text.trim()) {
    return [];
  }
  if (maxChars <= 0) {
    return [normalizeChunk(text)];
  }
  const chunks = [];
  let cursor = 0;
  while (cursor < text.length) {
    const remaining = text.slice(cursor);
    if (remaining.length <= maxChars) {
      const finalChunk = normalizeChunk(remaining);
      if (finalChunk) {
        chunks.push(finalChunk);
      }
      break;
    }
    const splitIndex = findBestSplitIndex(remaining, maxChars);
    const chunkText = normalizeChunk(remaining.slice(0, splitIndex));
    if (chunkText) {
      chunks.push(chunkText);
    }
    cursor += splitIndex;
    while (cursor < text.length && /\s/.test(text[cursor])) {
      cursor += 1;
    }
  }
  return chunks;
}

// src/services/SummarizationService.ts
function debugLog(enabled, event, metadata) {
  if (!enabled) {
    return;
  }
  if (metadata) {
    console.log(`[YTranscript][Debug] ${event}`, metadata);
    return;
  }
  console.log(`[YTranscript][Debug] ${event}`);
}
var _SummarizationService = class _SummarizationService {
  async summarize(text, options) {
    const language = "";
    const provider = (options == null ? void 0 : options.provider) || "ollama";
    const useChunking = this.shouldUseChunking(text, options);
    debugLog(options == null ? void 0 : options.enableDebugLogging, "LLM summarize start", {
      provider,
      model: (options == null ? void 0 : options.model) || "default",
      stream: false,
      chunking: useChunking
    });
    if (useChunking) {
      return this.summarizeLargeTextMapReduce(text, options, false);
    }
    const metadata = {
      promptTemplate: options == null ? void 0 : options.promptTemplate,
      videoTitle: options == null ? void 0 : options.videoTitle,
      sourceUrl: options == null ? void 0 : options.sourceUrl,
      videoId: options == null ? void 0 : options.videoId,
      llmProvider: options == null ? void 0 : options.llmProvider,
      modelName: options == null ? void 0 : options.modelName,
      createdAt: options == null ? void 0 : options.createdAt
    };
    if (provider === "ollama") {
      return this.summarizeWithOllama(text, {
        language,
        model: (options == null ? void 0 : options.model) || "qwen2.5:3b",
        baseUrl: (options == null ? void 0 : options.ollamaBaseUrl) || "http://localhost:11434",
        ...metadata
      });
    }
    if (provider === "openrouter") {
      return this.summarizeWithOpenRouter(text, {
        language,
        model: (options == null ? void 0 : options.model) || "openai/gpt-4o-mini",
        apiKey: (options == null ? void 0 : options.openRouterApiKey) || "",
        ...metadata
      });
    }
    if (provider === "openai") {
      return this.summarizeWithOpenAI(text, {
        language,
        model: (options == null ? void 0 : options.model) || "gpt-4o-mini",
        apiKey: (options == null ? void 0 : options.openAIApiKey) || "",
        ...metadata
      });
    }
    return `[Provider ${provider} not implemented yet]`;
  }
  async summarizeStream(text, options, onChunk) {
    const language = "";
    const provider = (options == null ? void 0 : options.provider) || "ollama";
    const useChunking = this.shouldUseChunking(text, options);
    debugLog(options == null ? void 0 : options.enableDebugLogging, "LLM summarize start", {
      provider,
      model: (options == null ? void 0 : options.model) || "default",
      stream: true,
      chunking: useChunking
    });
    if (useChunking) {
      return this.summarizeLargeTextMapReduce(text, options, true, onChunk);
    }
    const metadata = {
      promptTemplate: options == null ? void 0 : options.promptTemplate,
      videoTitle: options == null ? void 0 : options.videoTitle,
      sourceUrl: options == null ? void 0 : options.sourceUrl,
      videoId: options == null ? void 0 : options.videoId,
      llmProvider: options == null ? void 0 : options.llmProvider,
      modelName: options == null ? void 0 : options.modelName,
      createdAt: options == null ? void 0 : options.createdAt
    };
    if (provider === "ollama") {
      return this.summarizeWithOllamaStream(text, {
        language,
        model: (options == null ? void 0 : options.model) || "qwen2.5:3b",
        baseUrl: (options == null ? void 0 : options.ollamaBaseUrl) || "http://localhost:11434",
        ...metadata
      }, onChunk);
    }
    if (provider === "openrouter") {
      return this.summarizeWithChatCompletionsStream(
        text,
        {
          language,
          model: (options == null ? void 0 : options.model) || "openai/gpt-4o-mini",
          apiKey: (options == null ? void 0 : options.openRouterApiKey) || "",
          url: "https://openrouter.ai/api/v1/chat/completions",
          headers: {
            "HTTP-Referer": "https://obsidian.md",
            "X-Title": "Obsidian YTranscript"
          },
          ...metadata
        },
        onChunk
      );
    }
    if (provider === "openai") {
      return this.summarizeWithChatCompletionsStream(
        text,
        {
          language,
          model: (options == null ? void 0 : options.model) || "gpt-4o-mini",
          apiKey: (options == null ? void 0 : options.openAIApiKey) || "",
          url: "https://api.openai.com/v1/chat/completions",
          ...metadata
        },
        onChunk
      );
    }
    const fallback = `[Provider ${provider} not implemented yet]`;
    await onChunk(fallback, fallback);
    return fallback;
  }
  shouldUseChunking(text, options) {
    var _a;
    const enableChunking = (_a = options == null ? void 0 : options.enableChunking) != null ? _a : true;
    if (!enableChunking) {
      return false;
    }
    return text.trim().length > _SummarizationService.MAX_SINGLE_PASS_CHARS;
  }
  buildChunkedReduceInput(chunkSummaries) {
    return chunkSummaries.map((summary, index) => `### Chunk ${index + 1}
${summary.trim()}`).join("\n\n");
  }
  async summarizeLargeTextMapReduce(text, options, streamFinal, onChunk) {
    var _a;
    const chunks = splitIntoChunks(text, _SummarizationService.CHUNK_MAX_CHARS);
    const debugEnabled = options == null ? void 0 : options.enableDebugLogging;
    debugLog(debugEnabled, "Chunking active", {
      chunkCount: chunks.length,
      chunkMaxChars: _SummarizationService.CHUNK_MAX_CHARS
    });
    if (chunks.length <= 1) {
      const noChunkOptions = { ...options, enableChunking: false };
      if (streamFinal && onChunk) {
        return this.summarizeStream(text, noChunkOptions, onChunk);
      }
      return this.summarize(text, noChunkOptions);
    }
    const chunkConcurrencyRaw = (_a = options == null ? void 0 : options.chunkConcurrency) != null ? _a : _SummarizationService.DEFAULT_CHUNK_MAP_CONCURRENCY;
    const chunkConcurrency = Math.max(1, Math.floor(chunkConcurrencyRaw));
    const chunkSummaries = [];
    let processedChunks = 0;
    for (let i = 0; i < chunks.length; i += chunkConcurrency) {
      const batch = chunks.slice(i, i + chunkConcurrency);
      const batchSummaries = await Promise.all(
        batch.map(async (chunk, batchIndex) => {
          var _a2;
          const chunkIndex = i + batchIndex + 1;
          debugLog(debugEnabled, "Chunk summarize start", {
            chunk: `${chunkIndex}/${chunks.length}`,
            chunkSize: chunk.length
          });
          try {
            const chunkSummary = await this.summarize(chunk, {
              ...options,
              promptTemplate: _SummarizationService.CHUNK_PROMPT,
              enableChunking: false
            });
            debugLog(debugEnabled, "Chunk summarize ok", {
              chunk: `${chunkIndex}/${chunks.length}`
            });
            return chunkSummary;
          } catch (error) {
            const errorMessage = error instanceof Error ? error.message : String(error);
            debugLog(debugEnabled, "Chunk summarize failed", {
              chunk: `${chunkIndex}/${chunks.length}`,
              error: errorMessage
            });
            console.warn(`Chunk summarization failed at index ${i + batchIndex}:`, error);
            return "";
          } finally {
            processedChunks += 1;
            (_a2 = options == null ? void 0 : options.onChunkProgress) == null ? void 0 : _a2.call(options, processedChunks, chunks.length);
          }
        })
      );
      chunkSummaries.push(...batchSummaries.filter((summary) => summary.trim().length > 0));
    }
    if (chunkSummaries.length === 0) {
      throw new Error("All chunk summarization requests failed.");
    }
    const reduceInput = this.buildChunkedReduceInput(chunkSummaries);
    const finalOptions = { ...options, enableChunking: false };
    debugLog(debugEnabled, "Final merge start", {
      successfulChunks: chunkSummaries.length,
      stream: streamFinal
    });
    if (streamFinal && onChunk) {
      try {
        const finalSummary2 = await this.summarizeStream(reduceInput, finalOptions, onChunk);
        debugLog(debugEnabled, "Final merge ok", {
          summaryLength: finalSummary2.length
        });
        return finalSummary2;
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        debugLog(debugEnabled, "Final merge stream failed, falling back to non-streaming", {
          error: errorMessage
        });
      }
    }
    const finalSummary = await this.summarize(reduceInput, finalOptions);
    debugLog(debugEnabled, "Final merge ok", {
      summaryLength: finalSummary.length
    });
    if (streamFinal && onChunk) {
      await onChunk(finalSummary, finalSummary);
    }
    return finalSummary;
  }
  async summarizeWithOllama(text, options) {
    var _a;
    const prompt = this.buildPrompt(text, options.language, options);
    const baseUrl = options.baseUrl.replace(/\/$/, "");
    const response = await this.requestOllamaGenerateWithRetry(baseUrl, {
      model: options.model,
      prompt,
      stream: false
    });
    if (response.status >= 400) {
      const errorText = (response.text || "").trim();
      throw new Error(
        `Ollama request failed: ${response.status}${errorText ? ` - ${errorText}` : ""}`
      );
    }
    const data = response.json || JSON.parse(response.text);
    if (data.error) {
      throw new Error(`Ollama error: ${data.error}`);
    }
    return ((_a = data.response) == null ? void 0 : _a.trim()) || "[Empty summary returned by Ollama]";
  }
  async summarizeWithOllamaStream(text, options, onChunk) {
    const prompt = this.buildPrompt(text, options.language, options);
    const baseUrl = options.baseUrl.replace(/\/$/, "");
    let response;
    try {
      response = await this.fetchWithRetry(`${baseUrl}/api/generate`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: options.model,
          prompt,
          stream: true
        })
      });
    } catch (error) {
      console.warn("Ollama streaming request failed before response. Falling back to non-streaming request.", error);
      const fallbackSummary = await this.summarizeWithOllama(text, options);
      await onChunk(fallbackSummary, fallbackSummary);
      return fallbackSummary;
    }
    if (!response.ok) {
      const errorText = await this.safeReadResponseText(response);
      console.warn(
        `Ollama streaming failed (${response.status} ${response.statusText}). Falling back to non-streaming request.${errorText ? ` Details: ${errorText}` : ""}`
      );
      const fallbackSummary = await this.summarizeWithOllama(text, options);
      await onChunk(fallbackSummary, fallbackSummary);
      return fallbackSummary;
    }
    return this.readJsonLineStream(response, async (chunk, fullText) => {
      if (chunk.error) {
        throw new Error(`Ollama stream error: ${chunk.error}`);
      }
      if (chunk.response) {
        await onChunk(chunk.response, fullText + chunk.response);
      }
      return chunk.response || "";
    });
  }
  async summarizeWithOpenRouter(text, options) {
    var _a, _b, _c, _d, _e;
    if (!options.apiKey.trim()) {
      throw new Error("OpenRouter API key is missing.");
    }
    const prompt = this.buildPrompt(text, options.language, options);
    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${options.apiKey}`,
        "HTTP-Referer": "https://obsidian.md",
        "X-Title": "Obsidian YTranscript"
      },
      body: JSON.stringify({
        model: options.model,
        messages: [
          {
            role: "user",
            content: prompt
          }
        ]
      })
    });
    if (!response.ok) {
      const errorText = await this.safeReadResponseText(response);
      throw new Error(
        `OpenRouter request failed: ${response.status} ${response.statusText}${errorText ? ` - ${errorText}` : ""}`
      );
    }
    const data = await response.json();
    if ((_a = data.error) == null ? void 0 : _a.message) {
      throw new Error(`OpenRouter error: ${data.error.message}`);
    }
    return ((_e = (_d = (_c = (_b = data.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.message) == null ? void 0 : _d.content) == null ? void 0 : _e.trim()) || "[Empty summary returned by OpenRouter]";
  }
  async summarizeWithOpenAI(text, options) {
    var _a, _b, _c, _d, _e;
    if (!options.apiKey.trim()) {
      throw new Error("OpenAI API key is missing.");
    }
    const prompt = this.buildPrompt(text, options.language, options);
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${options.apiKey}`
      },
      body: JSON.stringify({
        model: options.model,
        messages: [
          {
            role: "user",
            content: prompt
          }
        ]
      })
    });
    if (!response.ok) {
      const errorText = await this.safeReadResponseText(response);
      throw new Error(
        `OpenAI request failed: ${response.status} ${response.statusText}${errorText ? ` - ${errorText}` : ""}`
      );
    }
    const data = await response.json();
    if ((_a = data.error) == null ? void 0 : _a.message) {
      throw new Error(`OpenAI error: ${data.error.message}`);
    }
    return ((_e = (_d = (_c = (_b = data.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.message) == null ? void 0 : _d.content) == null ? void 0 : _e.trim()) || "[Empty summary returned by OpenAI]";
  }
  async summarizeWithChatCompletionsStream(text, options, onChunk) {
    if (!options.apiKey.trim()) {
      throw new Error("API key is missing.");
    }
    const prompt = this.buildPrompt(text, options.language, options);
    const response = await this.fetchWithRetry(options.url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${options.apiKey}`,
        ...options.headers || {}
      },
      body: JSON.stringify({
        model: options.model,
        stream: true,
        messages: [
          {
            role: "user",
            content: prompt
          }
        ]
      })
    });
    if (!response.ok) {
      const errorText = await this.safeReadResponseText(response);
      throw new Error(
        `Chat completions stream request failed: ${response.status} ${response.statusText}${errorText ? ` - ${errorText}` : ""}`
      );
    }
    return this.readServerSentEventsStream(response, async (chunk, fullText) => {
      var _a, _b, _c, _d;
      if ((_a = chunk.error) == null ? void 0 : _a.message) {
        throw new Error(`Chat completions stream error: ${chunk.error.message}`);
      }
      const delta = ((_d = (_c = (_b = chunk.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.delta) == null ? void 0 : _d.content) || "";
      if (delta) {
        await onChunk(delta, fullText + delta);
      }
      return delta;
    });
  }
  async requestOllamaGenerateWithRetry(baseUrl, payload) {
    let attempt = 1;
    while (true) {
      const response = await (0, import_obsidian2.requestUrl)({
        url: `${baseUrl}/api/generate`,
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(payload)
      });
      const retryPolicy = this.getRetryPolicy(response.status);
      if (!_SummarizationService.RETRYABLE_STATUS_CODES.has(response.status) || attempt >= retryPolicy.maxAttempts) {
        return response;
      }
      const delayMs = this.getRetryDelayMs(response.status, attempt);
      await this.sleep(delayMs);
      attempt += 1;
    }
  }
  getRetryPolicy(status) {
    if (status === 429) {
      return { maxAttempts: 4, baseDelayMs: 2e3 };
    }
    if (status === 504) {
      return { maxAttempts: 3, baseDelayMs: 1e3 };
    }
    if (status === 503) {
      return { maxAttempts: 3, baseDelayMs: 500 };
    }
    return { maxAttempts: 1, baseDelayMs: 0 };
  }
  getRetryDelayMs(status, attempt, retryAfterSeconds) {
    if (typeof retryAfterSeconds === "number" && Number.isFinite(retryAfterSeconds) && retryAfterSeconds > 0) {
      return Math.floor(retryAfterSeconds * 1e3);
    }
    const policy = this.getRetryPolicy(status);
    const exponentialDelay = policy.baseDelayMs * 2 ** Math.max(0, attempt - 1);
    const jitter = Math.floor(Math.random() * 200);
    return exponentialDelay + jitter;
  }
  parseRetryAfterSeconds(response) {
    const retryAfter = response.headers.get("retry-after");
    if (!retryAfter) {
      return void 0;
    }
    const retryAfterValue = Number.parseInt(retryAfter, 10);
    return Number.isNaN(retryAfterValue) ? void 0 : retryAfterValue;
  }
  async fetchWithRetry(url, init) {
    let attempt = 1;
    while (true) {
      let response;
      try {
        response = await fetch(url, init);
      } catch (error) {
        if (attempt >= 3) {
          throw error;
        }
        await this.sleep(this.getRetryDelayMs(503, attempt));
        attempt += 1;
        continue;
      }
      const retryPolicy = this.getRetryPolicy(response.status);
      if (!_SummarizationService.RETRYABLE_STATUS_CODES.has(response.status) || attempt >= retryPolicy.maxAttempts) {
        return response;
      }
      const retryAfterSeconds = this.parseRetryAfterSeconds(response);
      await this.sleep(this.getRetryDelayMs(response.status, attempt, retryAfterSeconds));
      attempt += 1;
    }
  }
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  async safeReadResponseText(response) {
    try {
      return (await response.text()).trim();
    } catch (error) {
      console.warn("Failed to read error response body:", error);
      return "";
    }
  }
  async readJsonLineStream(response, handleChunk) {
    if (!response.body) {
      throw new Error("Streaming response body is empty.");
    }
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    let fullText = "";
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        const trimmedLine = line.trim();
        if (!trimmedLine) continue;
        const chunk = JSON.parse(trimmedLine);
        const delta = await handleChunk(chunk, fullText);
        fullText += delta;
      }
    }
    return fullText.trim();
  }
  async readServerSentEventsStream(response, handleChunk) {
    if (!response.body) {
      throw new Error("Streaming response body is empty.");
    }
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    let fullText = "";
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const events = buffer.split("\n\n");
      buffer = events.pop() || "";
      for (const event of events) {
        const dataLines = event.split("\n").map((line) => line.trim()).filter((line) => line.startsWith("data:"));
        for (const dataLine of dataLines) {
          const data = dataLine.replace(/^data:\s*/, "");
          if (!data || data === "[DONE]") continue;
          const chunk = JSON.parse(data);
          const delta = await handleChunk(chunk, fullText);
          fullText += delta;
        }
      }
    }
    return fullText.trim();
  }
  buildPrompt(text, language, metadata) {
    var _a;
    const userInstructions = ((_a = metadata.promptTemplate) == null ? void 0 : _a.trim()) ? this.replaceMetadataPlaceholders(metadata.promptTemplate.trim(), language, metadata) : [
      "Create a clear, structured Markdown summary of the following YouTube transcript.",
      "Focus on the key ideas, important details, named entities, practical steps and open questions."
    ].join("\n");
    return [
      "You are a precise YouTube transcript summarization assistant.",
      "Return only Markdown body content.",
      "Do not include YAML frontmatter.",
      "Do not include Obsidian Properties.",
      "Do not include metadata fields like title, source_url, video_id, llm_provider or created_at.",
      "Do not explain what you are doing.",
      "",
      "User summary instructions:",
      userInstructions,
      "",
      "Transcript:",
      text
    ].join("\n");
  }
  replaceMetadataPlaceholders(content, language, metadata) {
    return content.split("{{language}}").join(language).split("{{LANGUAGE}}").join(language).split("{{video_title}}").join(metadata.videoTitle || "").split("{{source_url}}").join(metadata.sourceUrl || "").split("{{video_id}}").join(metadata.videoId || "").split("{{llm_provider}}").join(metadata.llmProvider || "").split("{{model_name}}").join(metadata.modelName || "").split("{{created_at}}").join(metadata.createdAt || "").split("{{VIDEO_TITLE}}").join(metadata.videoTitle || "").split("{{SOURCE_URL}}").join(metadata.sourceUrl || "").split("{{VIDEO_ID}}").join(metadata.videoId || "").split("{{LLM_PROVIDER}}").join(metadata.llmProvider || "").split("{{MODEL_NAME}}").join(metadata.modelName || "").split("{{CREATED_AT}}").join(metadata.createdAt || "");
  }
};
_SummarizationService.MAX_SINGLE_PASS_CHARS = 12e3;
_SummarizationService.CHUNK_MAX_CHARS = 1e4;
_SummarizationService.DEFAULT_CHUNK_MAP_CONCURRENCY = 1;
_SummarizationService.RETRYABLE_STATUS_CODES = /* @__PURE__ */ new Set([429, 503, 504]);
_SummarizationService.CHUNK_PROMPT = [
  "Create a concise Markdown summary for this transcript chunk.",
  "Focus on core facts, key arguments and actionable steps.",
  "Return only Markdown body content.",
  "Do not include YAML or metadata fields."
].join("\n");
var SummarizationService = _SummarizationService;

// src/transcript-view.ts
var TRANSCRIPT_TYPE_VIEW = "transcript-view";
var TranscriptView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.videoData = [];
    this.summarizationService = new SummarizationService();
    this.plugin = plugin;
    this.isDataLoaded = false;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h4", { text: "Transcript" });
  }
  async onClose() {
    const leafIndex = this.getLeafIndex();
    this.plugin.settings.leafUrls.splice(leafIndex, 1);
  }
  /**
   * Gets the leaf index out of all of the open leaves
   * This assumes that the leaf order shouldn't changed, which is a fair assumption
   */
  getLeafIndex() {
    const leaves = this.app.workspace.getLeavesOfType(TRANSCRIPT_TYPE_VIEW);
    return leaves.findIndex((leaf) => leaf === this.leaf);
  }
  /**
   * Adds a div with loading text to the view content
   */
  renderLoader() {
    if (this.loaderContainerEl !== void 0) {
      this.loaderContainerEl.createEl("div", {
        text: "Loading..."
      });
    }
  }
  /**
   * Adds a text input to the view content
   */
  renderSearchInput(url, data, timestampMod) {
    const searchInputEl = this.contentEl.createEl("input");
    searchInputEl.type = "text";
    searchInputEl.placeholder = "Search...";
    searchInputEl.style.marginBottom = "20px";
    searchInputEl.addEventListener("input", (e) => {
      const searchFilter = e.target.value;
      this.renderTranscriptionBlocks(
        url,
        data,
        timestampMod,
        searchFilter
      );
    });
  }
  /**
   * Adds a div with the video title to the view content
   * @param title - the title of the video
   */
  renderVideoTitle(title) {
    const titleEl = this.contentEl.createEl("div");
    titleEl.innerHTML = title;
    titleEl.style.fontWeight = "bold";
    titleEl.style.marginBottom = "20px";
  }
  extractFullText(data) {
    return data.lines.map((line) => line.text).join(" ");
  }
  renderSummaryPlaceholder(summaryText, summaryLanguage) {
    if (this.summaryContainerEl === void 0) {
      this.summaryContainerEl = this.contentEl.createEl("div");
    } else {
      this.summaryContainerEl.empty();
    }
    this.summaryContainerEl.style.marginBottom = "20px";
    const headingEl = this.summaryContainerEl.createEl("div", {
      text: `Summary (${summaryLanguage || "de"})`
    });
    headingEl.style.fontWeight = "bold";
    headingEl.style.marginBottom = "8px";
    const bodyEl = this.summaryContainerEl.createEl("div", {
      text: summaryText
    });
    bodyEl.style.color = "var(--text-muted)";
    bodyEl.style.userSelect = "text";
    bodyEl.style.whiteSpace = "pre-wrap";
  }
  async loadPromptTemplate() {
    var _a;
    const path = (_a = this.plugin.settings.promptFilePath) == null ? void 0 : _a.trim();
    if (!path) {
      return void 0;
    }
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian3.TFile)) {
      return void 0;
    }
    return this.app.vault.cachedRead(file);
  }
  formatContentToPaste(url, blocks) {
    return blocks.map((block) => {
      const { quote, quoteTimeOffset } = block;
      const href = url + "&t=" + Math.floor(quoteTimeOffset / 1e3);
      const formattedBlock = `[${formatTimestamp(
        quoteTimeOffset
      )}](${href}) ${quote}`;
      return formattedBlock;
    }).join("\n");
  }
  /**
   * Add a transcription blocks to the view content
   * @param url - the url of the video
   * @param data - the transcript data
   * @param timestampMod - the number of seconds between each timestamp
   * @param searchValue - the value to search for in the transcript
   */
  renderTranscriptionBlocks(url, data, timestampMod, searchValue) {
    const dataContainerEl = this.dataContainerEl;
    if (dataContainerEl !== void 0) {
      dataContainerEl.empty();
      const transcriptBlocks = getTranscriptBlocks(
        data.lines,
        timestampMod
      );
      const filteredBlocks = transcriptBlocks.filter(
        (block) => block.quote.toLowerCase().includes(searchValue.toLowerCase())
      );
      filteredBlocks.forEach((block) => {
        const { quote, quoteTimeOffset } = block;
        const blockContainerEl = createEl("div", {
          cls: "yt-transcript__transcript-block"
        });
        blockContainerEl.draggable = true;
        const linkEl = createEl("a", {
          text: formatTimestamp(quoteTimeOffset),
          attr: {
            href: url + "&t=" + Math.floor(quoteTimeOffset / 1e3)
          }
        });
        linkEl.style.marginBottom = "5px";
        const span = dataContainerEl.createEl("span", {
          text: quote,
          title: "Click to copy"
        });
        span.addEventListener("click", (event) => {
          var _a;
          const target = event.target;
          if (target !== null) {
            navigator.clipboard.writeText((_a = target.textContent) != null ? _a : "");
          }
        });
        if (searchValue !== "") highlightText(span, searchValue);
        blockContainerEl.appendChild(linkEl);
        blockContainerEl.appendChild(span);
        blockContainerEl.addEventListener(
          "dragstart",
          (event) => {
            var _a;
            (_a = event.dataTransfer) == null ? void 0 : _a.setData(
              "text/html",
              blockContainerEl.innerHTML
            );
          }
        );
        blockContainerEl.addEventListener(
          "contextmenu",
          (event) => {
            const menu = new import_obsidian3.Menu();
            menu.addItem(
              (item) => item.setTitle("Copy all").onClick(() => {
                navigator.clipboard.writeText(
                  this.formatContentToPaste(
                    url,
                    filteredBlocks
                  )
                );
              })
            );
            menu.showAtPosition({
              x: event.clientX,
              y: event.clientY
            });
          }
        );
        dataContainerEl.appendChild(blockContainerEl);
      });
    }
  }
  /**
   * Sets the state of the view
   * This is called when the view is loaded
   */
  async setEphemeralState(state) {
    var _a;
    if (this.isDataLoaded) return;
    const leafIndex = this.getLeafIndex();
    this.summaryLanguage = state.summaryLanguage;
    if (state.url) {
      this.plugin.settings.leafUrls[leafIndex] = state.url;
      await this.plugin.saveSettings();
    }
    const { lang, country, timestampMod, leafUrls } = this.plugin.settings;
    const url = leafUrls[leafIndex];
    try {
      if (this.loaderContainerEl === void 0) {
        this.loaderContainerEl = this.contentEl.createEl("div");
      } else {
        this.loaderContainerEl.empty();
      }
      this.renderLoader();
      const data = await YoutubeTranscript.getTranscript(url, {
        lang,
        country
      });
      if (!data) throw Error();
      const fullText = this.extractFullText(data);
      const summaryText = await this.summarizationService.summarize(fullText, {
        language: this.summaryLanguage,
        provider: this.plugin.settings.provider,
        model: this.plugin.settings.model,
        ollamaBaseUrl: this.plugin.settings.ollamaBaseUrl,
        promptTemplate: await this.loadPromptTemplate(),
        enableChunking: this.plugin.settings.enableChunking,
        chunkConcurrency: this.plugin.settings.chunkConcurrency
      });
      console.log("Transcript full text:", fullText.slice(0, 200));
      console.log("Service summary:", summaryText);
      this.isDataLoaded = true;
      this.loaderContainerEl.empty();
      this.renderVideoTitle(data.title);
      this.renderSummaryPlaceholder(summaryText, this.summaryLanguage);
      if (this.summaryLanguage) {
        const languageEl = this.contentEl.createEl("div", {
          text: `Summary language: ${this.summaryLanguage}`
        });
        languageEl.style.marginBottom = "12px";
        languageEl.style.color = "var(--text-muted)";
        languageEl.style.fontSize = "var(--font-ui-small)";
      }
      this.renderSearchInput(url, data, timestampMod);
      if (this.dataContainerEl === void 0) {
        this.dataContainerEl = this.contentEl.createEl("div");
      } else {
        this.dataContainerEl.empty();
      }
      if (this.errorContainerEl !== void 0) {
        this.errorContainerEl.empty();
      }
      if (data.lines.length === 0) {
        this.dataContainerEl.createEl("h4", {
          text: "No transcript found"
        });
        this.dataContainerEl.createEl("div", {
          text: "Please check if video contains any transcript or try adjust language and country in plugin settings."
        });
      } else {
        this.renderTranscriptionBlocks(url, data, timestampMod, "");
      }
    } catch (err) {
      let errorMessage = "";
      if (err instanceof YoutubeTranscriptError) {
        errorMessage = err.message;
      }
      (_a = this.loaderContainerEl) == null ? void 0 : _a.empty();
      if (this.errorContainerEl === void 0) {
        this.errorContainerEl = this.contentEl.createEl("h5");
      } else {
        this.errorContainerEl.empty();
      }
      const titleEl = this.errorContainerEl.createEl("div", {
        text: "Error loading transcript"
      });
      titleEl.style.marginBottom = "5px";
      const messageEl = this.errorContainerEl.createEl("div", {
        text: errorMessage
      });
      messageEl.style.color = "var(--text-muted)";
      messageEl.style.fontSize = "var(--font-ui-small)";
    }
  }
  getViewType() {
    return TRANSCRIPT_TYPE_VIEW;
  }
  getDisplayText() {
    return "YouTube Transcript";
  }
  getIcon() {
    return "scroll";
  }
};

// src/url-utils.ts
var UrlPattern = /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;
function _getLinkNearestCursor(textLine, cursorPosition, linksInLine) {
  if (cursorPosition > textLine.length)
    throw new Error("Cursor out of the line");
  if (!linksInLine || linksInLine.length < 1)
    throw new Error("No links found");
  for (let i = 0; i < linksInLine.length; i++) {
    const link = linksInLine[i];
    const index = linksInLine.length > i + 1 ? textLine.indexOf(linksInLine[i + 1]) : textLine.length;
    if (cursorPosition <= index) return link;
  }
  throw new Error("Unexpected");
}
function getUrlFromText(lineText, cursorPosition) {
  var _a;
  const url = _getLinkNearestCursor(
    lineText,
    cursorPosition,
    (_a = lineText.match(UrlPattern)) != null ? _a : []
  );
  return [lineText.indexOf(url), lineText.indexOf(url) + url.length];
}

// editor-extensions.ts
var EditorExtensions = class {
  static getSelectedText(editor) {
    if (!editor.somethingSelected()) {
      const wordBoundaries = this.getWordBoundaries(editor);
      editor.setSelection(wordBoundaries[0], wordBoundaries[1]);
    }
    return editor.getSelection();
  }
  static getWordBoundaries(editor) {
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    const urlPosition = getUrlFromText(lineText, cursor.ch);
    return [
      { line: cursor.line, ch: urlPosition[0] },
      { line: cursor.line, ch: urlPosition[1] }
    ];
  }
};

// src/commands/insert-transcript.ts
var import_obsidian5 = require("obsidian");

// src/url-detection.ts
var URLDetector = class {
  /**
   * Checks if the provided URL is a valid YouTube URL
   * @param url - The URL to validate
   * @returns true if the URL is a valid YouTube URL, false otherwise
   */
  static isValidYouTubeUrl(url) {
    if (!url || typeof url !== "string") {
      return false;
    }
    try {
      const urlObj = new URL(url);
      const hostname = urlObj.hostname.toLowerCase();
      const isYouTubeDomain = this.YOUTUBE_DOMAINS.includes(hostname);
      if (!isYouTubeDomain) {
        return false;
      }
      if (hostname.includes("youtube.com")) {
        return urlObj.pathname === "/watch" && urlObj.searchParams.has("v");
      }
      if (hostname.includes("youtu.be")) {
        const pathParts = urlObj.pathname.split("/");
        return pathParts.length >= 2 && pathParts[1].length > 0;
      }
      return false;
    } catch (error) {
      return false;
    }
  }
  /**
   * Extracts the first valid YouTube URL found in the provided text
   * @param text - The text to search for YouTube URLs
   * @returns The first valid YouTube URL found, or null if none found
   */
  static extractYouTubeUrlFromText(text) {
    if (!text || typeof text !== "string") {
      return null;
    }
    const urlRegex = /https?:\/\/[^\s<>"{}|\\^`[\]]+/gi;
    const matches = text.match(urlRegex);
    if (!matches) {
      return null;
    }
    for (const match of matches) {
      if (this.isValidYouTubeUrl(match)) {
        return match;
      }
    }
    return null;
  }
  /**
   * Creates a YouTube URL with a timestamp parameter
   * @param url - The base YouTube URL
   * @param offsetMs - The timestamp offset in milliseconds
   * @returns The URL with timestamp parameter added
   */
  static buildTimestampUrl(url, offsetMs) {
    if (!url || typeof url !== "string") {
      return "";
    }
    try {
      const urlObj = new URL(url);
      const seconds = Math.max(0, Math.floor(offsetMs / 1e3));
      urlObj.searchParams.set("t", seconds.toString());
      return urlObj.toString();
    } catch (error) {
      return url;
    }
  }
};
// YouTube URL patterns to match various formats
URLDetector.YOUTUBE_URL_PATTERNS = [
  /https?:\/\/(?:www\.)?youtube\.com\/watch\?v=[\w-]+(?:[&?][\w=&-]*)?/gi,
  /https?:\/\/(?:www\.)?youtu\.be\/[\w-]+(?:[?][\w=&-]*)?/gi,
  /https?:\/\/(?:m\.)?youtube\.com\/watch\?v=[\w-]+(?:[&?][\w=&-]*)?/gi,
  /https?:\/\/(?:mobile\.)?youtube\.com\/watch\?v=[\w-]+(?:[&?][\w=&-]*)?/gi,
  /https?:\/\/(?:music\.)?youtube\.com\/watch\?v=[\w-]+(?:[&?][\w=&-]*)?/gi
];
// More comprehensive regex for matching YouTube URLs
URLDetector.YOUTUBE_DOMAINS = [
  "youtube.com",
  "www.youtube.com",
  "m.youtube.com",
  "mobile.youtube.com",
  "music.youtube.com",
  "youtu.be",
  "www.youtu.be"
];

// src/transcript-formatter.ts
var TranscriptFormatter = class {
  /**
   * Formats a transcript response according to the specified template and options
   * @param transcript - The transcript response to format
   * @param url - The source YouTube URL
   * @param options - Formatting options including template and timestamp frequency
   * @returns The formatted transcript string
   */
  static format(transcript, url, options) {
    if (!transcript || !transcript.lines || !Array.isArray(transcript.lines)) {
      return "";
    }
    if (transcript.lines.length === 0) {
      return "";
    }
    const normalizedOptions = this.normalizeOptions(options);
    const template = normalizedOptions.template || "standard" /* STANDARD */;
    switch (template) {
      case "minimal" /* MINIMAL */:
        return this.formatMinimalTemplate(
          transcript,
          url,
          normalizedOptions
        );
      case "standard" /* STANDARD */:
        return this.formatStandardTemplate(
          transcript,
          url,
          normalizedOptions
        );
      case "rich" /* RICH */:
        return this.formatRichTemplate(
          transcript,
          url,
          normalizedOptions
        );
      default:
        return this.formatStandardTemplate(
          transcript,
          url,
          normalizedOptions
        );
    }
  }
  /**
   * Convenience method to format transcript with minimal template
   */
  static formatMinimal(transcript, url, options) {
    return this.format(transcript, url, {
      ...options,
      template: "minimal" /* MINIMAL */
    });
  }
  /**
   * Convenience method to format transcript with standard template
   */
  static formatStandard(transcript, url, options) {
    return this.format(transcript, url, {
      ...options,
      template: "standard" /* STANDARD */
    });
  }
  /**
   * Convenience method to format transcript with rich template
   */
  static formatRich(transcript, url, options) {
    return this.format(transcript, url, {
      ...options,
      template: "rich" /* RICH */
    });
  }
  /**
   * Normalizes and validates formatting options
   */
  static normalizeOptions(options) {
    const normalized = {
      timestampMod: Math.max(1, Math.floor(options.timestampMod)) || 5,
      template: options.template || "standard" /* STANDARD */
    };
    if (options.timestampMod <= 0) {
      normalized.timestampMod = 1;
    }
    return normalized;
  }
  /**
   * Formats transcript as plain text without timestamps
   */
  static formatMinimalTemplate(transcript, url, options) {
    return transcript.lines.map((line) => line.text.trim()).filter((text) => text.length > 0).join(" ");
  }
  /**
   * Formats transcript with clickable timestamps
   */
  static formatStandardTemplate(transcript, url, options) {
    const blocks = getTranscriptBlocks(
      transcript.lines,
      options.timestampMod
    );
    if (blocks.length === 0) {
      return "";
    }
    return blocks.map((block) => {
      const { quote, quoteTimeOffset } = block;
      const timestampStr = formatTimestamp(quoteTimeOffset);
      const timestampUrl = url ? URLDetector.buildTimestampUrl(url, quoteTimeOffset) : "#";
      return `[${timestampStr}](${timestampUrl}) ${quote.trim()}`;
    }).join("\n");
  }
  /**
   * Formats transcript with metadata header and clickable timestamps
   */
  static formatRichTemplate(transcript, url, options) {
    const title = transcript.title && transcript.title.trim() ? transcript.title.trim() : "YouTube Transcript";
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const sourceUrl = url || "Unknown";
    const header = [
      `## ${title}`,
      `**Source**: ${sourceUrl}`,
      `**Retrieved**: ${today}`,
      ""
      // Empty line before transcript
    ].join("\n");
    const standardContent = this.formatStandardTemplate(
      transcript,
      url,
      options
    );
    return header + standardContent;
  }
};

// src/prompt-modal.ts
var import_obsidian4 = require("obsidian");
var PromptModal = class extends import_obsidian4.Modal {
  constructor(initialValue) {
    super(app);
    this.submitted = false;
    this.initialValue = initialValue;
    this.value = initialValue || "";
  }
  onOpen() {
    this.titleEl.setText("YouTube URL");
    this.createForm();
  }
  onClose() {
    this.contentEl.empty();
    if (!this.submitted) {
      this.reject();
    }
  }
  createForm() {
    new import_obsidian4.Setting(this.contentEl).setName("YouTube URL").addText((text) => {
      text.inputEl.style.width = "100%";
      text.setValue(this.value);
      text.onChange((value) => this.value = value);
      text.inputEl.addEventListener(
        "keydown",
        (evt) => this.enterCallback(evt)
      );
      if (this.initialValue) {
        text.inputEl.select();
      }
      text.inputEl.focus();
    });
    const buttonDiv = this.modalEl.createDiv();
    buttonDiv.addClass("modal-button-container");
    const submitButton = new import_obsidian4.ButtonComponent(buttonDiv);
    submitButton.buttonEl.addClass("mod-cta");
    submitButton.setButtonText("Submit").onClick((evt) => {
      this.resolveAndClose(evt);
    });
  }
  enterCallback(evt) {
    if (evt.key === "Enter") {
      this.resolveAndClose(evt);
    }
  }
  resolveAndClose(evt) {
    this.submitted = true;
    evt.preventDefault();
    this.resolve({
      url: this.value
    });
    this.close();
  }
  async openAndGetValue(resolve, reject) {
    this.resolve = resolve;
    this.reject = reject;
    this.open();
  }
};

// src/commands/insert-transcript.ts
var MAX_SINGLE_PASS_CHARS = 12e3;
var CHUNK_MAX_CHARS = 1e4;
var InsertTranscriptCommand = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.summarizationService = new SummarizationService();
  }
  /**
   * Executes the insert transcript command with default settings
   */
  async execute(editor) {
    await this.executeWithOptions(editor, {});
  }
  /**
   * Executes the insert transcript command with custom options
   */
  async executeWithOptions(editor, options) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q, _r, _s, _t, _u, _v, _w, _x, _y, _z, _A, _B, _C, _D, _E;
    let statusRequestId;
    try {
      const debugEnabled = ((_a = this.plugin.settings) == null ? void 0 : _a.enableDebugLogging) === true;
      debugLog(debugEnabled, "Insert transcript flow start");
      const promptInput = await this.getYouTubeUrlWithConfirmation(editor);
      if (!(promptInput == null ? void 0 : promptInput.url)) {
        return;
      }
      const { url } = promptInput;
      new import_obsidian5.Notice("Generating YouTube summary\u2026");
      const insertionStart = editor ? editor.getCursor() : null;
      const loadingText = [
        `## Summary`,
        "Generating summary\u2026",
        "",
        "## Transcript",
        "Loading transcript\u2026",
        ""
      ].join("\n");
      if (editor && insertionStart) {
        editor.replaceRange(loadingText, insertionStart);
      }
      if (!URLDetector.isValidYouTubeUrl(url)) {
        return;
      }
      statusRequestId = (_c = (_b = this.plugin).startStatusRequest) == null ? void 0 : _c.call(_b, "YT: Fetching transcript...");
      const transcriptConfig = this.createTranscriptConfig();
      const transcript = await YoutubeTranscript.getTranscript(
        url,
        transcriptConfig
      );
      if (!transcript || !transcript.lines || transcript.lines.length === 0) {
        (_e = (_d = this.plugin).completeStatusRequest) == null ? void 0 : _e.call(_d, statusRequestId, "YT: No transcript found");
        return;
      }
      (_g = (_f = this.plugin).setStatusForRequest) == null ? void 0 : _g.call(_f, statusRequestId, "YT: Transcript loaded");
      debugLog(debugEnabled, "Transcript loaded", {
        lineCount: transcript.lines.length
      });
      const fullText = transcript.lines.map((l) => l.text).join(" ");
      const promptTemplate = await this.loadPromptTemplate();
      const metadata = {
        videoTitle: transcript.title || "Untitled YouTube Video",
        sourceUrl: url,
        videoId: this.extractVideoId(url),
        llmProvider: ((_h = this.plugin.settings) == null ? void 0 : _h.provider) || "ollama",
        modelName: ((_i = this.plugin.settings) == null ? void 0 : _i.model) || "",
        createdAt: (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)
      };
      const formatOptions = this.mergeFormatOptions(options);
      const formattedTranscript = TranscriptFormatter.format(
        transcript,
        url,
        formatOptions
      );
      let currentOutputEnd = editor && insertionStart ? editor.offsetToPos(editor.posToOffset(insertionStart) + loadingText.length) : null;
      let lastStreamUpdate = 0;
      let streamedSummaryText = "";
      const chunkingEnabled = (_k = (_j = this.plugin.settings) == null ? void 0 : _j.enableChunking) != null ? _k : true;
      const chunkingActive = chunkingEnabled && fullText.trim().length > MAX_SINGLE_PASS_CHARS;
      const chunkCount = chunkingActive ? splitIntoChunks(fullText, CHUNK_MAX_CHARS).length : 1;
      const selectedModel = (_l = this.plugin.settings) == null ? void 0 : _l.model;
      if (!selectedModel) {
        new import_obsidian5.Notice("Please select a model in Settings before generating a summary.");
        this.openPluginSettings();
        (_n = (_m = this.plugin).completeStatusRequest) == null ? void 0 : _n.call(_m, statusRequestId, "YT: Missing model");
        const errorText = [
          "## Summary",
          "No model selected. Please choose a model in plugin settings.",
          "",
          "## Transcript",
          formattedTranscript,
          ""
        ].join("\n");
        if (editor && insertionStart && currentOutputEnd) {
          editor.replaceRange(errorText, insertionStart, currentOutputEnd);
        } else {
          await this.writeOutputToActiveFile(errorText);
        }
        return;
      }
      if (chunkingActive) {
        (_p = (_o = this.plugin).setStatusForRequest) == null ? void 0 : _p.call(
          _o,
          statusRequestId,
          `YT: Chunking 1/${chunkCount}...`
        );
      } else {
        (_r = (_q = this.plugin).setStatusForRequest) == null ? void 0 : _r.call(_q, statusRequestId, "YT: Generating summary...");
      }
      let finalMergeStarted = false;
      const summaryText = await this.summarizationService.summarizeStream(
        fullText,
        {
          provider: (_s = this.plugin.settings) == null ? void 0 : _s.provider,
          model: (_t = this.plugin.settings) == null ? void 0 : _t.model,
          ollamaBaseUrl: (_u = this.plugin.settings) == null ? void 0 : _u.ollamaBaseUrl,
          openRouterApiKey: (_v = this.plugin.settings) == null ? void 0 : _v.openRouterApiKey,
          openAIApiKey: (_w = this.plugin.settings) == null ? void 0 : _w.openAIApiKey,
          promptTemplate,
          videoTitle: metadata.videoTitle,
          sourceUrl: metadata.sourceUrl,
          videoId: metadata.videoId,
          llmProvider: metadata.llmProvider,
          modelName: metadata.modelName,
          createdAt: metadata.createdAt,
          enableChunking: (_x = this.plugin.settings) == null ? void 0 : _x.enableChunking,
          chunkConcurrency: (_y = this.plugin.settings) == null ? void 0 : _y.chunkConcurrency,
          enableDebugLogging: debugEnabled,
          onChunkProgress: (current, total) => {
            var _a2, _b2;
            if (!chunkingActive) {
              return;
            }
            (_b2 = (_a2 = this.plugin).setStatusForRequest) == null ? void 0 : _b2.call(
              _a2,
              statusRequestId,
              `YT: Chunking ${current}/${total}...`
            );
          }
        },
        async (_chunk, fullSummary) => {
          var _a2, _b2;
          if (!finalMergeStarted) {
            finalMergeStarted = true;
            (_b2 = (_a2 = this.plugin).setStatusForRequest) == null ? void 0 : _b2.call(_a2, statusRequestId, "YT: Final merge...");
          }
          if (!editor || !insertionStart || !currentOutputEnd) {
            return;
          }
          streamedSummaryText = fullSummary;
          const now = Date.now();
          if (now - lastStreamUpdate < 250) {
            return;
          }
          lastStreamUpdate = now;
          const liveOutput = this.buildOutput(
            streamedSummaryText || "Generating summary\u2026",
            formattedTranscript,
            metadata
          );
          editor.replaceRange(liveOutput, insertionStart, currentOutputEnd);
          currentOutputEnd = editor.offsetToPos(
            editor.posToOffset(insertionStart) + liveOutput.length
          );
        }
      );
      const output = this.buildOutput(
        summaryText,
        formattedTranscript,
        metadata
      );
      if (!output.trim()) return;
      if (editor && insertionStart && currentOutputEnd) {
        editor.replaceRange(output, insertionStart, currentOutputEnd);
      } else {
        await this.writeOutputToActiveFile(output);
      }
      await this.renameActiveNote(metadata.videoTitle);
      if (chunkingActive) {
        (_A = (_z = this.plugin).setStatusForRequest) == null ? void 0 : _A.call(
          _z,
          statusRequestId,
          `YT: Chunking ${chunkCount}/${chunkCount}...`
        );
      }
      (_C = (_B = this.plugin).completeStatusRequest) == null ? void 0 : _C.call(_B, statusRequestId, "YT: Done");
      debugLog(debugEnabled, "Final summary ready", {
        summaryLength: summaryText.length
      });
      new import_obsidian5.Notice("YouTube summary inserted.");
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      if (errorMessage.includes("429")) {
        new import_obsidian5.Notice("Rate limited by provider. Retried automatically but failed.");
      } else {
        new import_obsidian5.Notice("Failed to generate YouTube summary. Check developer console.");
      }
      if (statusRequestId !== void 0) {
        (_E = (_D = this.plugin).completeStatusRequest) == null ? void 0 : _E.call(_D, statusRequestId, "YT: Failed");
      }
      console.error("Insert transcript failed:", error);
    }
  }
  openPluginSettings() {
    var _a, _b, _c, _d;
    const app2 = this.plugin.app;
    (_b = (_a = app2.setting) == null ? void 0 : _a.open) == null ? void 0 : _b.call(_a);
    (_d = (_c = app2.setting) == null ? void 0 : _c.openTabById) == null ? void 0 : _d.call(_c, this.plugin.manifest.id);
  }
  /**
   * Gets YouTube URL with user confirmation via prompt
   * Always shows prompt, but pre-populates with detected URL
   */
  async getYouTubeUrlWithConfirmation(editor) {
    var _a;
    const detectedUrl = await this.detectYouTubeUrl(editor);
    try {
      const prompt = new PromptModal(detectedUrl || void 0);
      const result = await new Promise((resolve, reject) => {
        prompt.openAndGetValue(resolve, reject);
      });
      if (!((_a = result == null ? void 0 : result.url) == null ? void 0 : _a.trim())) {
        return null;
      }
      return {
        url: result.url.trim()
      };
    } catch (error) {
      return null;
    }
  }
  /**
   * Detects YouTube URL from selection or clipboard (for pre-populating prompt)
   */
  async detectYouTubeUrl(editor) {
    const selectionUrl = this.getUrlFromSelection(editor);
    if (selectionUrl) {
      return selectionUrl;
    }
    const clipboardUrl = await this.getUrlFromClipboard();
    if (clipboardUrl) {
      return clipboardUrl;
    }
    return null;
  }
  /**
   * Gets URL from current editor selection
   */
  getUrlFromSelection(editor) {
    if (!editor) {
      return null;
    }
    try {
      const selectedText = editor.somethingSelected() ? editor.getSelection() : EditorExtensions.getSelectedText(editor);
      return URLDetector.extractYouTubeUrlFromText(selectedText);
    } catch (error) {
      return null;
    }
  }
  /**
   * Gets URL from system clipboard
   */
  async getUrlFromClipboard() {
    try {
      const clipboardText = await navigator.clipboard.readText();
      return URLDetector.extractYouTubeUrlFromText(clipboardText);
    } catch (error) {
      return null;
    }
  }
  /**
   * Creates transcript config from plugin settings
   */
  createTranscriptConfig() {
    var _a, _b;
    return {
      lang: (_a = this.plugin.settings) == null ? void 0 : _a.lang,
      country: (_b = this.plugin.settings) == null ? void 0 : _b.country
    };
  }
  extractVideoId(url) {
    try {
      const parsedUrl = new URL(url);
      const videoId = parsedUrl.searchParams.get("v");
      if (videoId) return videoId;
      const pathParts = parsedUrl.pathname.split("/").filter(Boolean);
      return pathParts[pathParts.length - 1] || "";
    } catch (error) {
      return "";
    }
  }
  async loadPromptTemplate() {
    var _a, _b;
    const path = (_b = (_a = this.plugin.settings) == null ? void 0 : _a.promptFilePath) == null ? void 0 : _b.trim();
    if (!path) return void 0;
    const file = this.plugin.app.vault.getAbstractFileByPath(path);
    if (!file || file.extension !== "md" && file.extension !== "txt") return void 0;
    return this.plugin.app.vault.cachedRead(file);
  }
  buildOutput(summaryText, formattedTranscript, metadata) {
    const cleanedSummary = this.cleanSummaryBody(
      this.replaceMetadataPlaceholders(summaryText.trim(), metadata)
    );
    const extracted = this.extractBodyMetadata(cleanedSummary);
    const frontmatter = this.buildFrontmatter(
      metadata,
      extracted.tags,
      extracted.videoType
    );
    return [
      frontmatter,
      "",
      extracted.content || "Generating summary\u2026",
      "",
      "## Transcript",
      formattedTranscript,
      ""
    ].join("\n");
  }
  extractBodyMetadata(content) {
    const tags = /* @__PURE__ */ new Set(["youtube", "transcript"]);
    const outputLines = [];
    const lines = content.split("\n");
    let videoType;
    let isInsideTagsSection = false;
    let previousOutputWasDivider = false;
    const addTagsFromText = (tagText) => {
      tagText.replace(/^`+|`+$/g, "").split(/[\n,]+/).map((tag) => tag.replace(/^\s*[-*]\s*/, "")).map((tag) => tag.replace(/^#+/, "")).map((tag) => tag.replace(/`/g, "")).map((tag) => tag.trim()).filter(Boolean).forEach((tag) => tags.add(tag));
    };
    const isHeadingLine = (line) => /^#{1,6}\s+/.test(line.trim());
    const isBoldLabelLine = (line) => /^\*{0,2}[A-ZÄÖÜ][^\n]*\*{0,2}\s*$/.test(line.trim());
    const isDividerLine = (line) => /^---\s*$/.test(line.trim());
    const isInlineCodeTagList = (line) => {
      const value = line.trim();
      return /^`[^`]+`$/.test(value) && value.includes(",");
    };
    for (const line of lines) {
      const trimmedLine = line.trim();
      const normalizedLine = trimmedLine.replace(/\s{2,}$/, "");
      const inlineTagsMatch = normalizedLine.match(
        /^(?:#{1,6}\s*)?\*{0,2}Tags?\*{0,2}:\s*(.+)$/i
      );
      if (inlineTagsMatch == null ? void 0 : inlineTagsMatch[1]) {
        addTagsFromText(inlineTagsMatch[1]);
        isInsideTagsSection = false;
        continue;
      }
      const tagSectionHeaderMatch = normalizedLine.match(
        /^(?:#{1,6}\s*)?\*{0,2}Tags?\*{0,2}\s*$/i
      );
      if (tagSectionHeaderMatch) {
        isInsideTagsSection = true;
        continue;
      }
      if (isInlineCodeTagList(normalizedLine)) {
        addTagsFromText(normalizedLine);
        if (previousOutputWasDivider) {
          outputLines.pop();
          previousOutputWasDivider = false;
        }
        continue;
      }
      if (isInsideTagsSection) {
        if (!trimmedLine) {
          isInsideTagsSection = false;
          continue;
        }
        if (isHeadingLine(trimmedLine) || isBoldLabelLine(trimmedLine)) {
          isInsideTagsSection = false;
          outputLines.push(line);
          previousOutputWasDivider = isDividerLine(line);
          continue;
        }
        addTagsFromText(trimmedLine);
        continue;
      }
      const categoryMatch = normalizedLine.match(
        /^\*{0,2}Kategorie\*{0,2}:\s*(.+)$/i
      );
      if (categoryMatch == null ? void 0 : categoryMatch[1]) {
        videoType = categoryMatch[1].trim();
        continue;
      }
      outputLines.push(line);
      previousOutputWasDivider = isDividerLine(line);
    }
    return {
      content: outputLines.join("\n").trim(),
      tags: Array.from(tags),
      videoType
    };
  }
  cleanSummaryBody(content) {
    return content.replace(/^---[\s\S]*?---\s*/, "").replace(/\n---\s*$/g, "").trim();
  }
  replaceMetadataPlaceholders(content, metadata) {
    var _a, _b;
    return content.split("{{video_title}}").join(metadata.videoTitle).split("{{source_url}}").join(metadata.sourceUrl).split("{{video_id}}").join(metadata.videoId).split("{{language}}").join(((_a = this.plugin.settings) == null ? void 0 : _a.lang) || "").split("{{llm_provider}}").join(metadata.llmProvider).split("{{model_name}}").join(metadata.modelName).split("{{created_at}}").join(metadata.createdAt).split("{{VIDEO_TITLE}}").join(metadata.videoTitle).split("{{SOURCE_URL}}").join(metadata.sourceUrl).split("{{VIDEO_ID}}").join(metadata.videoId).split("{{LANGUAGE}}").join(((_b = this.plugin.settings) == null ? void 0 : _b.lang) || "").split("{{LLM_PROVIDER}}").join(metadata.llmProvider).split("{{MODEL_NAME}}").join(metadata.modelName).split("{{CREATED_AT}}").join(metadata.createdAt);
  }
  buildFrontmatter(metadata, tags, videoType) {
    var _a;
    return [
      "---",
      `title: ${this.quoteYaml(metadata.videoTitle)}`,
      `source_url: ${this.quoteYaml(metadata.sourceUrl)}`,
      `video_id: ${this.quoteYaml(metadata.videoId)}`,
      `language: ${((_a = this.plugin.settings) == null ? void 0 : _a.lang) || ""}`,
      `llm_provider: ${metadata.llmProvider}`,
      `llm_model: ${this.quoteYaml(metadata.modelName)}`,
      `created_at: ${metadata.createdAt}`,
      `tags: [${tags.map((tag) => this.quoteYaml(tag)).join(", ")}]`,
      videoType ? `video_type: ${this.quoteYaml(videoType)}` : void 0,
      "---"
    ].filter(Boolean).join("\n");
  }
  quoteYaml(value) {
    return JSON.stringify(value || "");
  }
  async writeOutputToActiveFile(output) {
    const activeFile = this.plugin.app.workspace.getActiveFile();
    if (!(activeFile instanceof import_obsidian5.TFile)) {
      return;
    }
    await this.plugin.app.vault.modify(activeFile, output);
  }
  async renameActiveNote(videoTitle) {
    var _a;
    const activeFile = this.plugin.app.workspace.getActiveFile();
    if (!(activeFile instanceof import_obsidian5.TFile)) return;
    const safeFileName = this.sanitizeFileName(videoTitle);
    if (!safeFileName) return;
    const currentFolder = ((_a = activeFile.parent) == null ? void 0 : _a.path) || "";
    const targetPath = await this.getAvailableFilePath(
      currentFolder,
      safeFileName,
      activeFile.path
    );
    if (targetPath === activeFile.path) return;
    await this.plugin.app.fileManager.renameFile(activeFile, targetPath);
  }
  sanitizeFileName(title) {
    return title.replace(/[\\/:*?"<>|]/g, " ").replace(/\s+/g, " ").trim().slice(0, 120).trim();
  }
  async getAvailableFilePath(folderPath, baseName, currentPath) {
    const normalizedFolder = folderPath && folderPath !== "/" ? `${folderPath}/` : "";
    let candidatePath = `${normalizedFolder}${baseName}.md`;
    if (candidatePath === currentPath) {
      return candidatePath;
    }
    let counter = 2;
    while (this.plugin.app.vault.getAbstractFileByPath(candidatePath)) {
      candidatePath = `${normalizedFolder}${baseName} ${counter}.md`;
      counter += 1;
    }
    return candidatePath;
  }
  /**
   * Merges user options with plugin settings
   */
  mergeFormatOptions(options) {
    var _a;
    return {
      template: options.template || "standard" /* STANDARD */,
      timestampMod: options.timestampMod || ((_a = this.plugin.settings) == null ? void 0 : _a.timestampMod) || 5
    };
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  timestampMod: 5,
  lang: "en",
  country: "EN",
  provider: "ollama",
  model: "qwen2.5:3b",
  availableModels: [],
  lastModelsByProvider: {},
  ollamaBaseUrl: "http://localhost:11434",
  openRouterApiKey: "",
  openAIApiKey: "",
  promptFilePath: "",
  outputFolder: "",
  enableChunking: true,
  chunkConcurrency: 1,
  enableDebugLogging: false,
  leafUrls: []
};
var YTranscriptPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.statusBarItemEl = null;
    this.statusResetTimer = null;
    this.activeStatusRequestId = 0;
  }
  async onload() {
    await this.loadSettings();
    this.statusBarItemEl = this.addStatusBarItem();
    this.statusBarItemEl.setText("YTranscript: Ready");
    this.insertTranscriptCommand = new InsertTranscriptCommand(this);
    this.registerView(
      TRANSCRIPT_TYPE_VIEW,
      (leaf) => new TranscriptView(leaf, this)
    );
    this.addCommand({
      id: "transcript-from-text",
      name: "Get YouTube transcript from selected url",
      editorCallback: (editor, _) => {
        const url = EditorExtensions.getSelectedText(editor).trim();
        this.openView(url);
      }
    });
    this.addCommand({
      id: "insert-youtube-transcript",
      name: "YouTube \u2192 AI Summary Note",
      callback: async () => {
        var _a;
        const target = await this.ensureActiveMarkdownEditor();
        if (!target.view) {
          new import_obsidian6.Notice("No markdown note available.");
          return;
        }
        if (!target.editor) {
          new import_obsidian6.Notice("No editor available. Writing note without live editor updates.");
        }
        await this.insertTranscriptCommand.execute((_a = target.editor) != null ? _a : void 0);
      }
    });
    this.addSettingTab(new YTranslateSettingTab(this.app, this));
  }
  async ensureActiveMarkdownEditor() {
    var _a;
    let view = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    if (!view) {
      const outputFolder = this.settings.outputFolder.trim();
      const folderPrefix = outputFolder ? `${outputFolder.replace(/\/$/, "")}/` : "";
      const file = await this.app.vault.create(
        `${folderPrefix}YouTube Transcript ${Date.now()}.md`,
        ""
      );
      const leaf = this.app.workspace.getLeaf(true);
      await leaf.openFile(file);
      view = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    }
    if (!view) {
      return { view: null, editor: null };
    }
    for (let attempt = 0; attempt < 3; attempt += 1) {
      const currentView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
      if (currentView == null ? void 0 : currentView.editor) {
        return { view: currentView, editor: currentView.editor };
      }
      await this.sleep(100 * (attempt + 1));
    }
    const fallbackView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    return { view: fallbackView || view, editor: (_a = fallbackView == null ? void 0 : fallbackView.editor) != null ? _a : null };
  }
  async sleep(ms) {
    await new Promise((resolve) => setTimeout(resolve, ms));
  }
  async openView(url, summaryLanguage) {
    const leaf = this.app.workspace.getRightLeaf(false);
    await leaf.setViewState({
      type: TRANSCRIPT_TYPE_VIEW
    });
    this.app.workspace.revealLeaf(leaf);
    leaf.setEphemeralState({
      url,
      summaryLanguage
    });
  }
  onunload() {
    if (this.statusResetTimer) {
      clearTimeout(this.statusResetTimer);
      this.statusResetTimer = null;
    }
    this.app.workspace.detachLeavesOfType(TRANSCRIPT_TYPE_VIEW);
  }
  startStatusRequest(initialText) {
    this.activeStatusRequestId += 1;
    const requestId = this.activeStatusRequestId;
    this.setStatusForRequest(requestId, initialText);
    return requestId;
  }
  setStatusForRequest(requestId, text) {
    var _a;
    if (requestId !== this.activeStatusRequestId) {
      return;
    }
    (_a = this.statusBarItemEl) == null ? void 0 : _a.setText(text);
    this.scheduleStatusReset(requestId);
  }
  completeStatusRequest(requestId, text) {
    this.setStatusForRequest(requestId, text);
  }
  scheduleStatusReset(requestId) {
    if (this.statusResetTimer) {
      clearTimeout(this.statusResetTimer);
    }
    this.statusResetTimer = setTimeout(() => {
      var _a;
      if (requestId !== this.activeStatusRequestId) {
        return;
      }
      (_a = this.statusBarItemEl) == null ? void 0 : _a.setText("YTranscript: Ready");
    }, 12e4);
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var YTranslateSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Settings for YTranscript" });
    new import_obsidian6.Setting(containerEl).setName("Timestamp interval").setDesc(
      "Indicates how often timestamp should occur in text (1 - every line, 10 - every 10 lines)"
    ).addText(
      (text) => text.setValue(this.plugin.settings.timestampMod.toFixed()).onChange(async (value) => {
        const v = Number.parseInt(value);
        this.plugin.settings.timestampMod = Number.isNaN(v) ? 5 : v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Language").setDesc("Preferred transcript language").addText(
      (text) => text.setValue(this.plugin.settings.lang).onChange(async (value) => {
        this.plugin.settings.lang = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Country").setDesc("Preferred transcript country code").addText(
      (text) => text.setValue(this.plugin.settings.country).onChange(async (value) => {
        this.plugin.settings.country = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("LLM Provider").setDesc("Select provider for summaries").addDropdown(
      (dropdown) => dropdown.addOption("ollama", "Ollama").addOption("openrouter", "OpenRouter").addOption("openai", "OpenAI").setValue(this.plugin.settings.provider).onChange(async (value) => {
        const previousProvider = this.plugin.settings.provider;
        if (this.plugin.settings.model) {
          this.plugin.settings.lastModelsByProvider[previousProvider] = this.plugin.settings.model;
        }
        this.plugin.settings.provider = value;
        this.plugin.settings.availableModels = [];
        this.plugin.settings.model = this.plugin.settings.lastModelsByProvider[value] || "";
        await this.plugin.saveSettings();
        this.display();
        await this.loadAndStoreModels({ silent: true });
        this.display();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Load Models").setDesc("Fetch available models from the selected provider").addButton(
      (button) => button.setButtonText("Load Models").onClick(async () => {
        try {
          await this.loadAndStoreModels({ silent: false });
          this.display();
        } catch (error) {
          console.error("Failed to load models:", error);
          new import_obsidian6.Notice("Failed to load models. Check developer console.");
        }
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Model").setDesc("Select a model. No default is set when provider changes.").addDropdown((dropdown) => {
      dropdown.addOption("", "\u2014 Select model \u2014");
      const modelSet = /* @__PURE__ */ new Set();
      this.plugin.settings.availableModels.forEach((model) => {
        modelSet.add(model);
      });
      Array.from(modelSet).sort((a, b) => a.localeCompare(b)).forEach((model) => {
        dropdown.addOption(model, model);
      });
      dropdown.setValue(this.plugin.settings.model || "").onChange(async (value) => {
        this.plugin.settings.model = value;
        if (value) {
          this.plugin.settings.lastModelsByProvider[this.plugin.settings.provider] = value;
        } else {
          delete this.plugin.settings.lastModelsByProvider[this.plugin.settings.provider];
        }
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(containerEl).setName("Ollama Base URL").setDesc("e.g. http://localhost:11434").addText(
      (text) => text.setValue(this.plugin.settings.ollamaBaseUrl).onChange(async (value) => {
        this.plugin.settings.ollamaBaseUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("OpenRouter API Key").addText(
      (text) => text.setValue(this.plugin.settings.openRouterApiKey).setPlaceholder("sk-...").onChange(async (value) => {
        this.plugin.settings.openRouterApiKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("OpenAI API Key").addText(
      (text) => text.setValue(this.plugin.settings.openAIApiKey).setPlaceholder("sk-...").onChange(async (value) => {
        this.plugin.settings.openAIApiKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Prompt File Path").setDesc("Vault path to a markdown/text prompt template").addText(
      (text) => text.setValue(this.plugin.settings.promptFilePath).setPlaceholder("Prompts/youtube-summary.md").onChange(async (value) => {
        this.plugin.settings.promptFilePath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Output Folder").setDesc("Vault folder for newly created YouTube summary notes. Leave empty for vault root.").addText(
      (text) => text.setValue(this.plugin.settings.outputFolder).setPlaceholder("04_Resources/YouTube").onChange(async (value) => {
        this.plugin.settings.outputFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Enable Chunking for long transcripts").setDesc("Recommended for long videos to avoid provider token limits.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableChunking).onChange(async (value) => {
        this.plugin.settings.enableChunking = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Chunk map concurrency").setDesc("Parallel chunk requests (1 = safest for local Ollama).").addText(
      (text) => {
        var _a;
        return text.setValue(String((_a = this.plugin.settings.chunkConcurrency) != null ? _a : 1)).onChange(async (value) => {
          const parsed = Number.parseInt(value, 10);
          this.plugin.settings.chunkConcurrency = Number.isNaN(parsed) ? 1 : Math.max(1, parsed);
          await this.plugin.saveSettings();
        });
      }
    );
    new import_obsidian6.Setting(containerEl).setName("Enable debug logging").setDesc("Logs safe pipeline metadata in developer console.").addToggle(
      (toggle) => {
        var _a;
        return toggle.setValue((_a = this.plugin.settings.enableDebugLogging) != null ? _a : false).onChange(async (value) => {
          this.plugin.settings.enableDebugLogging = value;
          await this.plugin.saveSettings();
        });
      }
    );
  }
  async loadAndStoreModels(options) {
    try {
      if (!options.silent) {
        new import_obsidian6.Notice("Loading models\u2026");
      }
      const models = await this.loadModelsForCurrentProvider();
      this.plugin.settings.availableModels = models;
      await this.plugin.saveSettings();
      if (!options.silent) {
        new import_obsidian6.Notice(`Loaded ${models.length} models.`);
      }
    } catch (error) {
      if (!options.silent) {
        throw error;
      }
      console.warn("Auto-loading models failed:", error);
    }
  }
  async loadModelsForCurrentProvider() {
    switch (this.plugin.settings.provider) {
      case "ollama":
        return this.loadOllamaModels();
      case "openrouter":
        return this.loadOpenRouterModels();
      case "openai":
        return this.loadOpenAIModels();
      default:
        return [];
    }
  }
  async loadOllamaModels() {
    var _a;
    const baseUrl = this.plugin.settings.ollamaBaseUrl.replace(/\/$/, "");
    const response = await (0, import_obsidian6.requestUrl)({
      url: `${baseUrl}/api/tags`,
      method: "GET"
    });
    const models = ((_a = response.json) == null ? void 0 : _a.models) || [];
    return models.map((model) => model.name).filter((name) => Boolean(name)).sort((a, b) => a.localeCompare(b));
  }
  async loadOpenRouterModels() {
    var _a;
    const apiKey = this.plugin.settings.openRouterApiKey.trim();
    if (!apiKey) {
      throw new Error("OpenRouter API key is missing.");
    }
    const response = await (0, import_obsidian6.requestUrl)({
      url: "https://openrouter.ai/api/v1/models",
      method: "GET",
      headers: {
        Authorization: `Bearer ${apiKey}`
      }
    });
    const models = ((_a = response.json) == null ? void 0 : _a.data) || [];
    return models.map((model) => model.id).filter((id) => Boolean(id)).sort((a, b) => a.localeCompare(b));
  }
  async loadOpenAIModels() {
    var _a;
    const apiKey = this.plugin.settings.openAIApiKey.trim();
    if (!apiKey) {
      throw new Error("OpenAI API key is missing.");
    }
    const response = await (0, import_obsidian6.requestUrl)({
      url: "https://api.openai.com/v1/models",
      method: "GET",
      headers: {
        Authorization: `Bearer ${apiKey}`
      }
    });
    const models = ((_a = response.json) == null ? void 0 : _a.data) || [];
    return models.map((model) => model.id).filter((id) => Boolean(id)).sort((a, b) => a.localeCompare(b));
  }
};
